[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"          # Vite ise "dist", Next.js için ".next", vs.

[build.environment]
  NODE_VERSION = "18"        # Projen hangi Node sürümünde derleniyorsa

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
